name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Run scalafix
      run: sbt scalafix

    - name: Run scalastyle
      run: sbt scalastyle

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Run tests
      run: sbt coverage test coverageReport

    - name: Upload coverage data
      env:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}

      run: bash <(curl -s -t "$codecov_token" https://codecov.io/bash)